// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/flame-lab/Particle.tsx": () => import("../components/mockups/flame-lab/Particle.tsx"),
  "./components/mockups/flame-lab/Studio.tsx": () => import("../components/mockups/flame-lab/Studio.tsx"),
  "./components/mockups/flame-lab/Volumetric.tsx": () => import("../components/mockups/flame-lab/Volumetric.tsx"),
  "./components/mockups/redesign-feed-first/Leaderboard.tsx": () => import("../components/mockups/redesign-feed-first/Leaderboard.tsx"),
  "./components/mockups/redesign-feed-first/Login.tsx": () => import("../components/mockups/redesign-feed-first/Login.tsx"),
  "./components/mockups/redesign-feed-first/Profile.tsx": () => import("../components/mockups/redesign-feed-first/Profile.tsx"),
  "./components/mockups/redesign-feed-first/Stakes.tsx": () => import("../components/mockups/redesign-feed-first/Stakes.tsx"),
  "./components/mockups/redesign-feed-first/TeamFeed.tsx": () => import("../components/mockups/redesign-feed-first/TeamFeed.tsx"),
  "./components/mockups/redesign-stakes-led/Leaderboard.tsx": () => import("../components/mockups/redesign-stakes-led/Leaderboard.tsx"),
  "./components/mockups/redesign-stakes-led/Login.tsx": () => import("../components/mockups/redesign-stakes-led/Login.tsx"),
  "./components/mockups/redesign-stakes-led/Profile.tsx": () => import("../components/mockups/redesign-stakes-led/Profile.tsx"),
  "./components/mockups/redesign-stakes-led/Stakes.tsx": () => import("../components/mockups/redesign-stakes-led/Stakes.tsx"),
  "./components/mockups/redesign-stakes-led/Today.tsx": () => import("../components/mockups/redesign-stakes-led/Today.tsx"),
  "./components/mockups/team-stakes/ActiveStake.tsx": () => import("../components/mockups/team-stakes/ActiveStake.tsx"),
  "./components/mockups/team-stakes/CreateStake.tsx": () => import("../components/mockups/team-stakes/CreateStake.tsx"),
  "./components/mockups/team-stakes/StakeResult.tsx": () => import("../components/mockups/team-stakes/StakeResult.tsx"),
  "./components/mockups/workout-cards/Current.tsx": () => import("../components/mockups/workout-cards/Current.tsx"),
  "./components/mockups/workout-cards/Furnace.tsx": () => import("../components/mockups/workout-cards/Furnace.tsx"),
  "./components/mockups/workout-cards/Holo.tsx": () => import("../components/mockups/workout-cards/Holo.tsx"),
  "./components/mockups/workout-cards/Inferno.tsx": () => import("../components/mockups/workout-cards/Inferno.tsx"),
  "./components/mockups/workout-cards/NeonHUD.tsx": () => import("../components/mockups/workout-cards/NeonHUD.tsx"),
  "./components/mockups/workout-cards/Plasma.tsx": () => import("../components/mockups/workout-cards/Plasma.tsx"),
  "./components/mockups/workout-cards/Telemetry.tsx": () => import("../components/mockups/workout-cards/Telemetry.tsx"),
  "./components/mockups/workout-cards/Trophy.tsx": () => import("../components/mockups/workout-cards/Trophy.tsx"),
  "./components/mockups/workout-cards/shared.tsx": () => import("../components/mockups/workout-cards/shared.tsx")
};
