// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/workout-cards/Current.tsx": () => import("../components/mockups/workout-cards/Current.tsx"),
  "./components/mockups/workout-cards/Furnace.tsx": () => import("../components/mockups/workout-cards/Furnace.tsx"),
  "./components/mockups/workout-cards/Holo.tsx": () => import("../components/mockups/workout-cards/Holo.tsx"),
  "./components/mockups/workout-cards/NeonHUD.tsx": () => import("../components/mockups/workout-cards/NeonHUD.tsx"),
  "./components/mockups/workout-cards/Plasma.tsx": () => import("../components/mockups/workout-cards/Plasma.tsx"),
  "./components/mockups/workout-cards/Telemetry.tsx": () => import("../components/mockups/workout-cards/Telemetry.tsx"),
  "./components/mockups/workout-cards/Trophy.tsx": () => import("../components/mockups/workout-cards/Trophy.tsx"),
  "./components/mockups/workout-cards/shared.tsx": () => import("../components/mockups/workout-cards/shared.tsx")
};
